name: Windows wolf build

on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker image list
        docker login -u "lamanchy" -p "${{ secrets.DOCKER_PASSWORD }}"
        Get-PSDrive C | Select-Object Used,Free
        docker build . --file docker\wolf_base\windows.Dockerfile --tag lamanchy/wolf_base --force-rm
        Get-PSDrive C | Select-Object Used,Free
        docker build . --file docker\wolf_app\windows.Dockerfile --tag lamanchy/wolf --force-rm
        Get-PSDrive C | Select-Object Used,Free
        docker push lamanchy/wolf
